;;; harness-core-test.el --- Tests for the module bus  -*- lexical-binding: t; -*-
;;; Code:

(require 'harness-test-helpers)
(require 'harness-http)

(ert-deftest harness-core-methods-roundtrip ()
  (harness-test-reset-bus)
  (harness-register-method 'test/add (lambda (a b) (+ a b)) :doc "add")
  (should (= 3 (harness-call 'test/add 1 2)))
  (should (harness-method-exists-p 'test/add))
  (should-error (harness-call 'test/missing) :type 'harness-no-such-method)
  (should (equal '(:name test/add :doc "add" :module nil :params nil)
                 (car (harness-methods)))))

(ert-deftest harness-core-call-async-wraps-values-and-errors ()
  (harness-test-reset-bus)
  (harness-register-method 'test/val (lambda () 42))
  (harness-register-method 'test/boom (lambda () (error "boom")))
  (should (= 42 (harness-await (harness-call-async 'test/val))))
  (should-error (harness-await (harness-call-async 'test/boom))))

(ert-deftest harness-core-events-priority-and-isolation ()
  (harness-test-reset-bus)
  (let (log)
    (harness-on 'test/ev (lambda (x) (push (list 'b x) log)) 60)
    (harness-on 'test/ev (lambda (_x) (error "ignored")) 10)
    (harness-on 'test/ev (lambda (x) (push (list 'a x) log)) 20)
    (harness-on '* (lambda (ev args) (push (list 'any ev args) log)))
    (should (= 3 (harness-emit 'test/ev 1)))
    (should (equal '((any test/ev (1)) (b 1) (a 1)) log))))

(ert-deftest harness-core-events-dedupe-and-off ()
  (harness-test-reset-bus)
  (let ((n 0))
    (defalias 'harness-test--counter (lambda () (cl-incf n)))
    (harness-on 'test/ev #'harness-test--counter)
    (let ((h (harness-on 'test/ev #'harness-test--counter)))
      (harness-emit 'test/ev)
      (should (= n 1))
      (harness-off h)
      (harness-emit 'test/ev)
      (should (= n 1)))))

(ert-deftest harness-core-sync-filter ()
  (harness-test-reset-bus)
  (harness-add-filter 'test/f (lambda (v _ctx) (* v 2)) 20)
  (harness-add-filter 'test/f (lambda (v ctx) (+ v ctx)) 10)
  (should (= 8 (harness-run-filter 'test/f 1 3))))

(ert-deftest harness-core-async-filter-chain-and-final ()
  (harness-test-reset-bus)
  (harness-add-filter 'test/af (lambda (v next) (run-at-time 0.01 nil next (plist-put v :a t))) 10)
  (harness-add-filter 'test/af (lambda (v next) (funcall next (plist-put v :b t))) 20)
  (harness-add-filter 'test/af (lambda (v _next) (harness-resolved (plist-put v :c t))) 30)
  (let ((r (harness-await (harness-run-filter-async 'test/af (list :start t)))))
    (should (plist-get r :a)) (should (plist-get r :b)) (should (plist-get r :c)))
  ;; :final stops the chain.
  (harness-add-filter 'test/af2 (lambda (v next) (funcall next (plist-put v :final t))) 10)
  (harness-add-filter 'test/af2 (lambda (v next) (funcall next (plist-put v :never t))) 20)
  (should-not (plist-get (harness-await (harness-run-filter-async 'test/af2 nil)) :never)))

(ert-deftest harness-core-promises ()
  (let ((p (harness-make-promise)))
    (should-not (harness-promise-settled-p p))
    (harness-resolve p 1)
    (should (= 2 (harness-await (harness-then p #'1+)))))
  (let ((p (harness-rejected '(error "x"))))
    (should (equal 'recovered (harness-await (harness-then p nil (lambda (_e) 'recovered))))))
  (should (equal '(1 2 3) (harness-await (harness-all (list (harness-resolved 1) 2 (harness-resolved 3))))))
  (let ((p (harness-with-promise (resolve _reject) (run-at-time 0.01 nil resolve 'later))))
    (should (eq 'later (harness-await p))))
  (should-error (harness-await (harness-with-promise (_r _j) (error "inside")))))

(ert-deftest harness-core-promise-chains-do-not-recurse ()
  ;; A long chain of promises resolving one another must not grow the stack.
  (let ((max-lisp-eval-depth 800)
        (p (harness-resolved 0)))
    (dotimes (_ 3000)
      (setq p (harness-then p #'1+)))
    (should (= 3000 (harness-await p))))
  ;; Nested adoption: each promise resolved with the next one.
  (let ((max-lisp-eval-depth 800)
        (head (harness-make-promise)) (cur nil))
    (setq cur head)
    (dotimes (_ 3000)
      (let ((next (harness-make-promise)))
        (harness-resolve cur next)
        (setq cur next)))
    (harness-resolve cur 'end)
    (should (eq 'end (harness-await head)))))

(ert-deftest harness-core-modules-order-and-failure-isolation ()
  (harness-test-reset-bus)
  (let (order)
    (harness-define-module 'c :requires '(b) :init (lambda () (push 'c order)))
    (harness-define-module 'a :init (lambda () (push 'a order)))
    (harness-define-module 'b :requires '(a) :init (lambda () (push 'b order)))
    (harness-define-module 'bad :init (lambda () (error "nope")))
    (harness-define-module 'dep-on-bad :requires '(bad) :init (lambda () (push 'never order)))
    (let ((ready (harness-modules-init)))
      (should (equal '(a b c) (reverse order)))
      (should (equal '(a b c) (sort (copy-sequence ready) (lambda (x y) (string< x y)))))
      (should (eq 'failed (harness-module-state (harness-module-get 'bad))))
      (should (eq 'failed (harness-module-state (harness-module-get 'dep-on-bad)))))
    ;; Redefinition keeps a ready module ready.
    (harness-define-module 'a :doc "new doc" :init (lambda () (push 'again order)))
    (should (harness-module-ready-p 'a))
    (harness-modules-init)
    (should-not (memq 'again order))))

(ert-deftest harness-core-defmethod-records-module ()
  (harness-test-reset-bus)
  (let ((harness--defining-module 'demo))
    (eval '(harness-defmethod test/hello (name) "Say hello." (format "hi %s" name)) t))
  (should (equal "hi x" (harness-call 'test/hello "x")))
  (should (eq 'demo (plist-get (car (harness-methods)) :module))))

(ert-deftest harness-util-json-conventions ()
  (should (equal "{\"a\":1,\"b\":[1,2],\"c\":null,\"d\":false,\"e\":true,\"f\":{},\"g\":[]}"
                 (harness-json-encode '(:a 1 :b (1 2) :c nil :d :false :e t :f :empty :g []))))
  (should (equal '(:a 1 :b (1 2) :c nil :d :false)
                 (harness-json-parse "{\"a\":1,\"b\":[1,2],\"c\":null,\"d\":false}")))
  (should (equal "[{\"x\":1}]" (harness-json-encode '((:x 1)))))
  (should (equal "{\"lines\":[2,30]}" (harness-json-encode '(:lines (2 . 30))))))

(ert-deftest harness-util-json-encode-text ()
  ;; Since Emacs 30 `harness-json-encode' gives bytes, which become raw-byte
  ;; characters inside other text and then cannot be encoded again.  The
  ;; text variant gives characters.
  (let* ((s "\N{U+2717} caf\N{U+E9} \N{U+D7} \N{U+2026}")
         (obj (list :s s))
         (text (harness-json-encode-text obj)))
    (should (multibyte-string-p text))
    (should (equal (concat "{\"s\":\"" s "\"}") text))
    (should (equal obj (harness-json-parse text)))
    ;; The same bytes on the wire either way.
    (should (equal (encode-coding-string text 'utf-8-unix)
                   (encode-coding-string (harness-json-encode obj) 'utf-8-unix)))
    ;; Inside other text, and that text inside other JSON, it stays text.
    (let ((outer (format "Input (JSON):\n%s\nNote: %s" text s)))
      (should (equal outer (plist-get (harness-json-parse (harness-json-encode (list :text outer))) :text)))))
  (should (equal "{\"a\":[1,\"b\"]}" (harness-json-encode-text '(:a (1 "b"))))))

(ert-deftest harness-util-misc ()
  (should (= 36 (length (harness-uuid))))
  (should (equal "12.3k" (harness-format-tokens 12345)))
  (should (equal "1.20M" (harness-format-tokens 1200000)))
  (should (equal "abc…xyz" (harness-truncate-middle "abcdefghijklmnopqrstuvwxyz" 7)))
  (should (harness-path-within-p "/tmp" "/tmp/a/b"))
  (should-not (harness-path-within-p "/tmp/a" "/tmp/ab"))
  (should (harness-fuzzy-score "hcl" "harness-core.el"))
  (should-not (harness-fuzzy-score "zzz" "harness"))
  (should (equal '("harness-core.el" "harness-http.el")
                 (sort (harness-fuzzy-filter "hel" '("readme" "harness-core.el" "harness-http.el"))
                       #'string<))))

(ert-deftest harness-util-senders ()
  "Who sent a message reads the same before and after JSON (kind a string)."
  (let* ((system (harness-sender-system "tasks"))
         (session (harness-sender-session '(:id "s1" :name "Fix the parser" :model "x")))
         (parsed (harness-json-parse (harness-json-encode system))))
    (should (equal '(:kind system :source "tasks") system))
    (should (equal '(:kind session :id "s1" :name "Fix the parser") session))
    (should (equal '(:kind "system" :source "tasks") parsed))
    (should (eq 'system (harness-sender-kind parsed)))
    (should (eq 'session (harness-sender-kind session)))
    ;; The user: no sender, or nothing that names a kind.
    (dolist (none '(nil (:source "x") (:kind nil) (:kind "") (:kind :false)))
      (should-not (harness-sender-kind none)))
    (should (equal parsed (harness-node-sender (list :kind 'user :meta (list :steering t :from parsed)))))
    (should-not (harness-node-sender '(:kind user :meta (:steering t))))
    (should-not (harness-node-sender '(:kind user :meta (:from (:source "x")))))
    (should (equal "the harness (tasks)" (harness-sender-description parsed)))
    (should (equal "the harness" (harness-sender-description '(:kind system))))
    (should (equal "session s1 \"Fix the parser\"" (harness-sender-description session)))
    (should (equal "session s2" (harness-sender-description '(:kind "session" :id "s2"))))
    (should (equal "the user" (harness-sender-description nil)))))

(ert-deftest harness-http-sse-parser ()
  (let (events)
    (let ((f (harness-http-sse-parser (lambda (ev data) (push (cons ev data) events)))))
      (funcall f "event: ping\ndata: {\"a\":1}\n\n: comment\ndata: line1\ndata: li")
      (funcall f "ne2\n\n"))
    (should (equal '(("ping" . "{\"a\":1}") (nil . "line1\nline2")) (reverse events)))))

(ert-deftest harness-loader-start-and-reload-with-temp-module ()
  (harness-test-reset-bus)
  (let* ((dir (harness-test-temp-dir))
         (moddir (expand-file-name "lisp/modules" dir))
         (file (expand-file-name "harness-demo.el" moddir)))
    (make-directory moddir t)
    (with-temp-file file
      (insert ";;; -*- lexical-binding: t -*-\n(harness-define-module 'demo :init (lambda () (harness-register-method 'demo/ping (lambda () 'pong))))\n(provide 'harness-demo)\n"))
    (cl-letf (((symbol-function 'harness--path)
               (lambda (rel) (expand-file-name rel dir))))
      (let ((harness-module-directories '("lisp/modules"))
            (harness--core-files nil)
            (harness-process nil))
        (should (harness-start))
        (should (eq 'pong (harness-call 'demo/ping)))
        (should (harness-module-ready-p 'demo))
        ;; A broken edit is refused and leaves the old definitions intact.
        (with-temp-file file (insert "(harness-define-module 'demo :init (lambda () (oops"))
        (should-not (harness-reload))
        (should (eq 'pong (harness-call 'demo/ping)))
        ;; A good edit is picked up.
        (with-temp-file file
          (insert ";;; -*- lexical-binding: t -*-\n(harness-define-module 'demo :init #'ignore)\n(harness-register-method 'demo/ping (lambda () 'pong2))\n(provide 'harness-demo)\n"))
        (should (harness-reload))
        (should (eq 'pong2 (harness-call 'demo/ping)))))
    (delete-directory dir t)))

(ert-deftest harness-util-run-command ()
  (let ((r (harness-await (harness-run-command '("sh" "-c" "echo out; echo err >&2; exit 3")))))
    (should (= 3 (plist-get r :exit)))
    (should (equal "out\n" (plist-get r :stdout)))
    (should (equal "err\n" (plist-get r :stderr))))
  (should (equal "abc" (plist-get (harness-await (harness-run-command '("cat") :stdin "abc")) :stdout)))
  (should (eq 'timeout (plist-get (harness-await (harness-run-command '("sleep" "5") :timeout 0.2)) :exit))))

(provide 'harness-core-test)
;;; harness-core-test.el ends here
